# Generated by Django 5.1 on 2025-01-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_date_joined_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(db_column='Zdjęcie profilowe', default='media/pfps/blank_user.png', upload_to='media/pfps/'),
        ),
    ]
