# Generated by Django 5.1 on 2024-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Users', models.CharField(db_column='Uzytkownicy', max_length=100)),
                ('Hours', models.DateTimeField(db_column='Godziny')),
            ],
        ),
        migrations.DeleteModel(
            name='Test1',
        ),
    ]
