# Generated by Django 5.1 on 2024-09-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_booking_delete_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Users', models.CharField(db_column='Uzytkownicy', max_length=100)),
                ('Hours', models.DateTimeField(db_column='Godziny')),
            ],
        ),
    ]
