# Generated by Django 5.1 on 2024-09-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0004_alter_booking_current_day_alter_booking_end_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keycodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Kod_Skrytki', max_length=4)),
                ('code_date', models.DateField(db_column='Data dodania')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='current_day',
            field=models.DateField(db_column='Data', help_text='Wybierz dzien'),
        ),
    ]
