# Generated by Django 5.1 on 2024-09-07 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0005_alter_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hours',
        ),
        migrations.AddField(
            model_name='archive',
            name='current_day',
            field=models.DateTimeField(db_column='Data', default=datetime.date(2024, 9, 1)),
        ),
        migrations.AddField(
            model_name='archive',
            name='end_hour',
            field=models.DateTimeField(db_column='Koniec', default=datetime.time(0, 0, 1)),
        ),
        migrations.AddField(
            model_name='archive',
            name='start_hour',
            field=models.DateTimeField(db_column='Start', default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='archive',
            name='users_amount',
            field=models.IntegerField(db_column='Ilosc osob', default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='current_day',
            field=models.DateTimeField(db_column='Data', default=datetime.date(2024, 9, 1)),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_hour',
            field=models.DateTimeField(db_column='Koniec', default=datetime.time(0, 0, 1)),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_hour',
            field=models.DateTimeField(db_column='Start', default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='booking',
            name='users_amount',
            field=models.IntegerField(db_column='Ilosc osob', default=0),
        ),
        migrations.AlterField(
            model_name='archive',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archive',
            name='users',
            field=models.CharField(db_column='Uzytkownicy', default='User', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='users',
            field=models.CharField(db_column='Uzytkownicy', default='User', max_length=100),
        ),
    ]
