# Generated by Django 5.1 on 2024-09-07 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0006_remove_archive_hours_remove_booking_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='end_hour',
            field=models.TimeField(db_column='Koniec', default=datetime.time(0, 0, 1)),
        ),
        migrations.AlterField(
            model_name='archive',
            name='start_hour',
            field=models.TimeField(db_column='Start', default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_hour',
            field=models.TimeField(db_column='Koniec', default=datetime.time(0, 0, 1)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_hour',
            field=models.TimeField(db_column='Start', default=datetime.time(0, 0)),
        ),
    ]
