# Generated by Django 5.1 on 2024-09-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0008_alter_archive_current_day_alter_archive_end_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='current_day',
            field=models.DateTimeField(db_column='Data', default='7/9/2024'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='current_day',
            field=models.DateTimeField(db_column='Data', default='7/9/2024'),
        ),
    ]
