# Generated by Django 5.1 on 2024-09-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0003_alter_archive_current_day_alter_booking_current_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='current_day',
            field=models.DateField(db_column='Data', help_text='wybierz date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_hour',
            field=models.TimeField(db_column='Koniec', help_text="Ta godzina moze byc 'na oko'"),
        ),
    ]
