# Generated by Django 5.1 on 2024-09-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0005_keycodes_alter_booking_current_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycodes',
            name='code',
            field=models.CharField(db_column='Kod_Skrytki', help_text='Cztery cyfry 0-9', max_length=4),
        ),
    ]
