# Generated by Django 5.1 on 2024-09-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0006_alter_keycodes_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_text', models.CharField(db_column='Opis bledu', help_text='Opisz problem, jakie kroki zrobiles zanim sie pojawil', max_length=600)),
                ('report_date', models.DateField(db_column='Data zgloszenia', help_text='Data dnia wystapienia problemu')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='current_day',
            field=models.DateField(db_column='Data', help_text='Wybierz dzień'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_hour',
            field=models.TimeField(db_column='Koniec', help_text="Ta godzina moze byc 'na oko', format taki sam jak powyżej"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_hour',
            field=models.TimeField(db_column='Start', help_text='Przykładowy format: 12:20'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='users',
            field=models.CharField(db_column='Uzytkownicy', help_text='Podana nazwa musi być nazwą zarejestrowanego użytkownika', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='users_amount',
            field=models.IntegerField(db_column='Ilosc_osob', help_text='Podaj jako numer'),
        ),
    ]
