# Generated by Django 5.1 on 2024-09-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0007_bugreports_alter_booking_current_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreports',
            name='report_text',
            field=models.CharField(db_column='Opis bledu', help_text='Opisz problem, jakie kroki zrobiles zanim sie pojawil', max_length=1000),
        ),
    ]
