# Generated by Django 5.1 on 2024-10-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0008_alter_bugreports_report_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='users_amount',
            field=models.IntegerField(db_column='Ilosc_osob'),
        ),
    ]
