# Generated by Django 5.1 on 2025-02-02 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0010_alter_archive_options_booking_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='archive',
            constraint=models.CheckConstraint(condition=models.Q(('users_amount__gt', 0)), name='archive_users_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('users_amount__gt', 0)), name='booking_users_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='keycodes',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^\\d{4}$')), name='code_must_be_4_digits'),
        ),
    ]
