# Generated by Django 5.1 on 2025-02-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0011_archive_archive_users_amount_gt_0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.TextField(db_column='Nazwa_Użytkownika')),
                ('period_start', models.DateField(db_column='Okres obowiązywania start')),
                ('period_end', models.DateField(db_column='Okres obowiązywania koniec')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningScheduleArchive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.TextField(db_column='Nazwa_Użytkownika')),
                ('period_start', models.DateField(db_column='Okres obowiązywania start')),
                ('period_end', models.DateField(db_column='Okres obowiązywania koniec')),
            ],
        ),
    ]
