# Generated by Django 5.1 on 2025-02-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0012_cleaningschedule_cleaningschedulearchive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaningschedule',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='cleaningschedulearchive',
            old_name='user',
            new_name='username',
        ),
    ]
