# Generated by Django 5.1 on 2024-09-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='current_day',
            field=models.DateTimeField(db_column='Data', help_text='Wpisz w formacie rok-miesiac-dzien (np. 2024-09-01)'),
        ),
    ]
